### ISSUE TITLE
Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by timsar2** [vugar005/ngx-awesome-uploader#7] opened 2019-07-16 07:57 UTC
after using advance sample, when i select an image i got error:
Cannot read property 'apply' of undefined
    at FilePickerComponent.handleFiles (ngx-awesome-uploader.js:301)

**Comment by vugar005** [comment] 2019-07-16 19:20
Hi @timsar2 
Do you use custom validator function ? If so, it is because your custom validator function is not returning boolean observable.

**Comment by timsar2** [comment] 2019-07-17 04:56
yes, im useing custom validator from advanced example of ngx-awesome-uploader.
i found rxjs import { of }  from 'rxjs' not available for ("@angular/core": "5.2.11", "rxjs": "^5.5.11")
it must come from => import { of } from 'rxjs/observable/of'

**Comment by vugar005** [comment] 2019-07-17 05:09
@timsar2 ok. can you confirm the problem is fixed now ?

**Comment by timsar2** [comment] 2019-07-17 05:21
> 
> 
> @timsar2 ok. can you confirm the problem is fixed now ?

i dont know it's right solution or not but to fix this i changed 
 **fesm5\ngx-awesome-uploader.js**  like this:

```
remove => import { of, combineLatest, Subject, timer } from 'rxjs';
import { of} from 'rxjs/observable/of';
import { combineLatest } from 'rxjs/observable/combineLatest';
import { Subject} from 'rxjs/Subject';
import { timer } from 'rxjs/observable/timer';
```

**Comment by vugar005** [comment] 2019-07-17 05:27
@timsar2 no it is not solution. According to documentation [learnrxjs.io](https://www.learnrxjs.io/operators/creation/of.htm), `of`  is imported directly from `rxjs`. Ok thank you for feedback , the issue would be investigated.

**Comment by timsar2** [comment] 2019-07-17 05:38
> 
> 
> @timsar2 no it is not solution. According to documentation [learnrxjs.io](https://www.learnrxjs.io/operators/creation/of.htm), `of` is imported directly from `rxjs`. Ok thank you for feedback , the issue would be investigated.

yes its imported directly from rxjs but in version "rxjs": "^5.5.11" it's not

**Comment by vugar005** [comment] 2019-08-08 13:04
@timsar2 The library uses Rxjs 6 syntax which is not compatible with Angular version using Rxjs 5 syntax. You should use Angular >=6 version .Thank you for feedback. I am going to update readme.md .

**Closed** 2019-08-08 13:05 UTC
